import Icon from 'components/Icon/Icon';
export const partners = [
  <Icon
    id="facebook"
    width={120}
    height={120}
    className="partners-contacts-icon"
  />,
  <Icon
    id="phone"
    width={120}
    height={120}
    className="partners-contacts-icon"
  />,
  <Icon
    id="facebook"
    width={120}
    height={120}
    className="partners-contacts-icon"
  />,
  <Icon
    id="facebook"
    width={120}
    height={120}
    className="partners-contacts-icon"
  />,
  <Icon
    id="facebook"
    width={120}
    height={120}
    className="partners-contacts-icon"
  />,
];
